input type:touchpad {
    natural_scroll enabled
    drag_lock disabled
    dwt enabled
    tap enabled
    tap_button_map lrm
    scroll_factor 0.4
    pointer_accel -0.1
}

seat seat0 xcursor_theme Adwaita 30

output * scale 1.5

include /etc/sway/config.d/*