#! /bin/awk -f

function ceil(n) {
    return n - int(n) > 0 ? int(n + 1) : n
}

function map(x, sx, ex, sy, ey) {
    return (x - sx) * (ey - sy) / (ex - sx) + sy
}

function getIcon(percentage, icons, len) {
    return icons[ceil(map(percentage, 0, 100, 1, len))]
}

BEGIN {
    dilen = split(" ", dischargingIcons, "")
    cilen = split(" ", chargingIcons, "")
    full_icon =""
    not_charging_icon = ""
    unknown_icon = ""

    while (("battery-info" | getline) > 0) {
        $3 = tolower($3)
        
        if ($3 == "discharging") {
            icon = getIcon($2, dischargingIcons, dilen)
        } else if ($3 == "charging") {
            icon = getIcon($2, chargingIcons, cilen)
        } else if ($3 == "full") {
            icon = full_icon
        } else if ($3 == "not charging") {
            icon = not_charging_icon
        } else {
            icon = unknown_icon
        }
    }
    
    printf("%s %d%% %s\n", icon, $2, $4)
    printf("%s %d%%\n", icon, $2)
    print $2 | "lineargradient lv 100 hv 0"
}
