#! /bin/awk -f

function ceil(n) {
    return n - int(n) > 0 ? int(n + 1) : n
}

function dischargingIcon(percentage) {
    return dischargingIcons[ceil((percentage / 100) * dilen)]
}

BEGIN {
    dilen = split("▁▂▃▄▅▆▇█", dischargingIcons, "")
    charging_icon = "🔌"
    full_icon =" ⚡"
    not_charging_icon = "🛑"
    almost_discharged_icon="❗️"
    unknown_icon = "♻"

    while (("battery-info" | getline) > 0) {
        $3 = tolower($3)
        
        if ($3 == "discharging") {
            icon = dischargingIcon($2)
        } else if ($3 == "charging") {
            icon = charging_icon
        } else if ($3 == "full") {
            icon = full_icon
        } else if ($3 == "not charging") {
            icon = not_charging_icon
        } else {
            icon = unknown_icon
        }
    }
    
    printf("%s %d%% %s\n", icon, $2, $4)
    printf("%s %d%%\n", icon, $2)
    print $2 | "lineargradient lv 100 hv 0"
}
