#! /bin/bash

muteicon="(muted)"
unmuteicon="🎙️"

# vol=$(pactl list sinks | grep '^[[:space:]]Volume:' | grep -oE '[0-9]{1,3}%')
# muted=$(pactl list sinks | grep '^[[:space:]]Mute:' | awk '{print $2 == "yes" ? 1 : 0}')

#1 left
#2 middle
#3 right
case "$BLOCK_BUTTON" in
    1|2|3) eval "$TERMINAL -e $AUDIO_CONTROL";;
esac

vol="$(pamixer --source 1 --get-volume)"

if [ "$(pamixer --source 1 --get-mute)" = "true" ]; then
    icon="$muteicon"
else
	icon="$unmuteicon"
fi

echo "$icon $vol%"
