#! /bin/bash

#1 left
#2 middle
#3 right
case "$BLOCK_BUTTON" in
    1|2|3) eval "$TERMINAL -e $TASK_MANAGER";;
esac

lowicon=""
midicon=""
highicon=""
lowtemp="20"
hightemp="60"

temp=$(sensors | grep "Core 0" | awk '{print $3}')

level="$(map sx "$lowtemp" ex "$hightemp" sy 0 ey 3 <<< "$temp" | awk '{print int($0)}')"

if [ "$level" -eq 0 ]
then
    icon="$lowicon"
elif [ "$level" -eq 1 ]
then
    icon="$midicon"
else
    icon="$highicon"
fi

echo "$icon $temp"
echo "$temp"
lineargradient lv "$lowtemp" hv "$hightemp" <<< "$temp"
