#! /bin/bash

muteicon="婢"
zeroicon=""
mediumicon="墳"
highicon=""

# vol=$(pactl list sinks | grep '^[[:space:]]Volume:' | grep -oE '[0-9]{1,3}%')
# muted=$(pactl list sinks | grep '^[[:space:]]Mute:' | awk '{print $2 == "yes" ? 1 : 0}')

#1 left
#2 middle
#3 right
case "$BLOCK_BUTTON" in
    1|2|3) eval "$TERMINAL -e $AUDIO_CONTROL";;
esac

vol="$(pamixer --get-volume)"

if [ "$(pamixer --get-mute)" = "true" ]; then
    icon="$muteicon"
elif [ "$vol" -gt "70" ]; then
	icon="$highicon"
elif [ "$vol" -lt "30" ]; then
	icon="$zeroicon"
else
	icon="$mediumicon"
fi

echo "$icon $vol%"
