#!/bin/bash

# options to be displayed
option0="screen"
option1="area"
option2="window"

# options to be displyed
options="$option0\n$option1\n$option2\n"

selected="$(printf '%s\n%s\n%s\n' "$option0" "$option1" "$option2" | rofi -lines 3 -dmenu -p "scrot")"
case $selected in
    $option0)
        sleep 1 && screenshot ;;
    $option1)
        screenshot -s
    $option2)
        sleep 1 && screenshot -u
esac
