#! /bin/env node

const fs = require("fs");
const NeuralNetwork = require("./neuralnet");

function printHelp() {
    console.log(
`neural [options]

perform tasks with a neural network.

OPTIONS:

-help                prints this help
-predict             goes into predict mode (default is train mode)
-layerout n          in prediction mode, outputs only the specified layer (negative numbers to output them all)
-datafile FILE       specify dataset file (default is stdin)
-modelfile FILE      specify model file (default is stdin)
-newnet              generates new neural network instead of reading one
-activation AF       specify activation function (default is ${activation})
-rate R              specify learning rate (default is ${rate})
-epochs E            specify number of epochs (default is ${epochs})
-hiddendims ...DIMS  specify dimensions of hidden layers (list terminated with --)`
);
}

const args = process.argv.slice(2);
if (!args.length) {
    args.push("-help");
}

let trainflag = true;
let layerout = null;
let datafile = "/dev/stdin";
let modelfile = "/dev/stdin";
let newnetflag = false;
let activation = "sigmoid";
let hiddendims = [];
let rate = 0.1;
let epochs = 100;
for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
        case "-help":
            printHelp();
            process.exit(0);
            break;
        case "-predict":
            trainflag = false;
            break;
        case "-layerout":
            i++;
            layerout = parseInt(args[i]);
            break;
        case "-datafile":
            i++;
            datafile = args[i];
            break;
        case "-modelfile":
            i++;
            modelfile = args[i];
            break;
        case "-newnet":
            newnetflag = true;
            break;
        case "-activation":
            i++;
            activation = args[i];
            break;
        case "-rate":
            i++;
            rate = Math.abs(+args[i]);
            break;
        case "-epochs":
            i++;
            epochs = Math.abs(Math.floor(+args[i]));
            break;
        case "-hiddendims":
            i++;
            while (i < args.length && args[i] !== "--") {
                hiddendims.push(Math.abs(Math.floor(+args[i++])));
            }
            break;
        default:
            console.error(`unknown option ${args[i]}`);
            process.exit(1);
            break;
    }
}

try {
    const data = loadData(datafile);
    if (trainflag) {
        train(data);
    } else {
        predict(data);
    }
} catch (e) {
    console.error(e.message);
}

function train(data) {
    const inputdim = data[0].input.length || 1;
    const outputdim = data[0].target.length || 1;
    let nn;
    if (newnetflag) {
        nn = new NeuralNetwork([inputdim, ...hiddendims, outputdim], activation);
    } else {
        nn = loadNeuralNetwork(modelfile);
    }
    nn.backpropagateDataset(data, rate, epochs);
    console.log(nn.serialize());
}

function predict(data) {
    const nn = loadNeuralNetwork(modelfile);
    for (const { input } of data) {
        let output;
        if (layerout !== null) {
            output = nn.outputHistoryArray(input);
            if (layerout >= output.length)
                throw new Error(`index out or range: length ${output.length}, index ${layerout}`);
            if (layerout >= 0)
                output = output[layerout];
        } else {
            output = nn.outputArray(input);
        }
        console.log(output);
    }
}

function loadNeuralNetwork(file) {
    return NeuralNetwork.deserialize(fs.readFileSync(file, "utf-8"));
}

function loadData(file) {
    return JSON.parse(fs.readFileSync(file, "utf-8"));
}
