#! /bin/env node

const fs = require("fs");
const util = require("util");
const NeuralNetwork = require("./neuralnet");

function printHelp() {
    console.log(
`neural [options]

perform tasks with a neural network.

OPTIONS:

-help                prints this help
-train               goes into train mode (default is ${mode} mode)
-predict             goes into predict mode (default is ${mode} mode)
-test                goes into test mode (default is ${mode} mode)
-layerout n          in prediction mode, outputs only the specified layer (negative numbers to output them all)
-data FILE           specify dataset file 
-model FILE          specify model file 
-activation AF       specify activation function (default is ${activation})
-rate R              specify learning rate (default is ${rate})
-epochs E            specify number of epochs (default is ${epochs})
-hiddendims ...DIMS  specify dimensions of hidden layers (list terminated with --)
-printtrace          prints stack trace when there is an error (for debugging)`
);
}

function printError(message) {
    console.error(message);
    process.exit(1);
}

function printDeep(obj) {
    console.log(util.inspect(obj, {
        showHidden: false, 
        depth: null, 
        colors: true,
        maxArrayLength: null,
    }));
}

const args = process.argv.slice(2);
if (!args.length) {
    args.push("-help");
}

let mode = "train";
let layerout = null;
let datafile = null;
let modelfile = null;
let activation = "relu";
let hiddendims = [];
let rate = 0.1;
let epochs = 100;
let printtrace = false;
for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
        case "-help":
            printHelp();
            process.exit(0);
            break;
        case "-train":
            mode = "train";
            break;
        case "-predict":
            mode = "predict";
            break;
        case "-test":
            mode = "test";
            break;
        case "-layerout":
            i++;
            layerout = parseInt(args[i]);
            break;
        case "-data":
            i++;
            datafile = args[i];
            break;
        case "-model":
            i++;
            modelfile = args[i];
            break;
        case "-activation":
            i++;
            activation = args[i];
            break;
        case "-rate":
            i++;
            rate = Math.abs(+args[i]);
            break;
        case "-epochs":
            i++;
            epochs = Math.abs(Math.floor(+args[i]));
            break;
        case "-hiddendims":
            i++;
            while (i < args.length && args[i] !== "--") {
                if (args[i].startsWith("-")) {
                    i--;
                    break;
                }
                hiddendims.push(Math.abs(Math.floor(+args[i++])));
            }
            break;
        case "-printtrace":
            printtrace = true;
            break;
        default:
            printError(`unknown option ${args[i]}`);
            break;
    }
}

if (datafile === null) {
    printError(`unspecified dataset file`);
}

try {
    const data = loadData(datafile);
    const inputdim = data[0].input.length || 1;
    const outputdim = data[0].target?.length || 1;
    const nn = modelfile !== null ? loadNeuralNetwork(modelfile) : 
        new NeuralNetwork([inputdim, ...hiddendims, outputdim], activation);
    switch (mode) {
        case "train":
            train(nn, data);
            break;
        case "predict":
            predict(nn, data);
            break;
        case "test":
            test(nn, data);
            break;
    }
} catch (e) {
    if (printtrace) {
        console.error(e);
    } else {
        printError(e.message);
    }
}

function train(nn, data) {
    nn.trainDataset(data, rate, epochs);
    console.log(nn.serialize());
}

function predict(nn, data) {
    for (const { input } of data) {
        let output;
        if (layerout !== null) {
            output = nn.outputHistory(input);
            if (layerout >= output.length)
                throw new Error(`index out or range: length ${output.length}, index ${layerout}`);
            if (layerout >= 0)
                output = output[layerout];
        } else {
            output = nn.output(input);
        }
        printDeep(output);
    }
}

function test(nn, data) {
    printDeep(nn.testDataset(data));
}

function loadNeuralNetwork(file) {
    return NeuralNetwork.deserialize(fs.readFileSync(file, "utf-8"));
}

function loadData(file) {
    return JSON.parse(fs.readFileSync(file, "utf-8"));
}
