Section "InputClass"
        Identifier "touchpad libinput"
        MatchIsTouchpad "on"
        Driver "libinput"
        Option "Tapping" "on"
        Option "TappingButtonMap" "lrm"
        Option "TappingDrag" "on"
        Option "DisableWhileTyping" "on"
        Option "NaturalScrolling" "on"
        Option "AccelSpeed" "0.02"
        Option "ScrollMethod" "twofinger"
        Option "ScrollFactor" "0.5"
        Option "ClickMethod" "clickfinger"
EndSection
