#!/bin/bash

findall() {
    fd --hidden --print0 "$@"
}

findall "$@" | fzf --ansi \
    --prompt="$PWD/" \
    --no-multi \
    --read0 \
    --print0 \
    --preview=$'fpreviewer -f {}' | xargs -0 printf '%s:1:0\0'
