#!/bin/bash

manargs() {
    awk '{gsub(/\(|\)/, "", $2); print $2, $1}' | xargs -r man 2>/dev/null
}

export -f manargs

man -k . | fzf --prompt='Man> ' --preview $'printf \'%s\' {} | manargs' | manargs
