#!/bin/bash

die() {
    printf '%s\n' "$@" >&2
    exit 1
}

cmdexists() {
    command -v "$1" >/dev/null 2>&1
}

mbat() {
    local start="$1"
    local end="$2"
    local ln="$3"
    local file="$4"

    if cmdexists bat; then
        bat --highlight-line "$ln" \
            --paging never \
            --color always \
            --number \
            --theme ansi \
            --line-range "$start":"$end" \
            "$file"
    else
        awk '
            NR == '$ln' {
                underbeg = "\033[4m"
                underend = "\033[0m"
            }
            NR >= '$start' {
                printf("%s%d %s%s\n", underbeg, NR, $0, underend)
                underbeg = ""
                underend = ""
            }
            NR > '$end' {
                exit
            }
        ' "$file"
    fi
}

file=/dev/stdin
linenr=1
while getopts ':f:l:' o; do
    case $o in
        f) file=$OPTARG ;;
        l) linenr=$OPTARG ;;
        :) die "must supply argument to '$OPTARG'" ;;
        ?) die "unknown option '$OPTARG'" ;;
    esac
done

[[ -e $file ]] || die "file '$file' does not exist"
positiveintre='^[0-9]+$'
[[ $linenr =~ $re ]] || die "invalid line number '$linenr'"

shopt -s checkwinsize; (:)
center=$((LINES / 2))
start=$((linenr - center > 0 ? linenr - center : 1))
end=$((start + LINES))

mbat "$start" "$end" "$linenr" "$file"
