#!/usr/bin/env bash

splitter() {
    local regex
    regex='(.+?)//([0-9]+): (.*)'
    IFS= read -r -d ''
    if [[ $REPLY =~ $regex ]]; then
        file="${BASH_REMATCH[1]}"
        linenr="${BASH_REMATCH[2]}"
        rest="${BASH_REMATCH[3]}"
        printf '%s:%d:0\0' "$file" "$linenr"
    fi
}

export -f splitter

previewer() {
    local f
    local n
    f="$1"
    n="${2%%:*}"
    fpreviewer -f "$f" -l "$n"
}

export -f previewer

rgcommand() {
    rgargs=(
        --hidden
        --null
        --line-number
        --no-heading
        --with-filename
        --line-buffered
    )
    rg ${rgargs[*]} "$@" | while IFS= read -r -d '' file; do
        IFS=: read -r linenr rest
        printf '%s//%d: %s\0' "$file" "$linenr" "$rest"
    done 
}

export -f rgcommand

fzfargs=(
    --ansi
    --no-multi
    --delimiter '//'
    --read0
    --print0
    --query ''
    --preview 'previewer {1} {2}'
)

[[ -n $FRG_RELOAD ]] && fzfargs+=(--bind "change:reload(rgcommand -- {q} || true)" --disabled)

rgcommand '' | fzf "${fzfargs[@]}" | splitter
