#! /bin/bash

print_help() {
    cat << EOF
install-dotfiles [options]

Install dotfiles found in a git repo.

-h    Show this help
-r    Specify the repo. Default is $repo
-d    Specify the destination folder. Default is $destination
-c    Specify separate-git-dir. Default is $confDir
EOF
}

git_bare() {
    # $1 -> destination
    # $2 -> confDir
    /usr/bin/git --git-dir="$1/$2" --work-tree="$1" "${@:3}"
}

clone_dotfiles() {
    # $1 -> path to repo
    # $2 -> directory to copy to
    # $3 -> separate-git-dir (.myconf)
    /usr/bin/git clone --bare "$1" "$2/$3"
}

repo="https://github.com/fioriandrea/dotfiles"
destination="$HOME"
confDir=".myconf"

while getopts ":hr:d:c:" o
do
    case "$o" in
        "h") print_help && exit 0 ;;
        "r") repo="$OPTARG" ;;
        "d") destination="$OPTARG" ;;
        "c") confDir="$OPTARG" ;;
        ":") echo "must supply argument to '$OPTARG'" >&2 && exit 1 ;;
        "?") echo "unknown option '$OPTARG'" >&2 && exit 1 ;;
    esac
done

shift "$(($OPTIND - 1))"

tmpdir="$(mktemp -d)"
if ! [ -d "$tmpdir" ]
then
    echo "failed to create tmpdir" >&2
    exit 2
fi

tmpdir="${tmpdir%/}"
destination="${destination%/}"

clone_dotfiles "$repo" "$tmpdir" "$confDir"
git_bare "$tmpdir" "$confDir" checkout
git_bare "$tmpdir" "$confDir" config --local status.showUntrackedFiles no
rsync -av --progress "$tmpdir"/ "$destination"

rm -rf "$tmpdir"
