#!/bin/sh

file=$1
read -r line < "$file"
case $line in
    \#!*)
        line=${line#\#!}
        $line "$file"
        exit 0
    ;;
esac

directory=$(dirname "$file")
directory=$(cd "$directory" && pwd)
file=$(basename "$file")
filename=${file%.*}
extension=${file##*.}
shift

cd "$directory" || exit 1

case "$extension" in
    py) python "$file" "$@" ;;
    js) node "$file" "$@" ;;
    ts) deno run -A "$file" "$@" ;;
    awk) awk -f "$file" "$@" ;;
    sh) sh "$file" "$@" ;;
    bash) bash "$file" "$@" ;;
    go) go run "$file" "$@" ;;
    m) octave "$file" "$@" ;;
    pl) perl "$file" "$@" ;;
    c) cc "$file" -o "$filename" && ./"$filename" ;;
    c++) g++ "$file" -o "$filename" && ./"$filename" ;;
    rs) rustc "$file" -o "$filename" && ./"$filename" ;;
    hs) runghc "$file" ;;
    *) echo "file format not supported '$extension'" >&2 ;;
esac
