#! /bin/sh

print_help() {
    cat << EOF
ltranslate [options]

Helper script to access the libretranslate API

-h    Prints help
-m    Sets mode, supported modes are 'translate', 'detect' and 'languages'. Default is '$mode'
-f    Source language (from). Default is '$from'
-t    Destination language (to). Deafult is '$to'
-c    Text to translate (content). Deafult is '$content'
EOF
}

post_json() {
    curl "$1" -X POST -H "Content-Type: application/json" -d "$2"
}

mode="translate"
from="en"
to="it"
content="Hello"
url="https://libretranslate.com"
while getopts ":hm:f:t:c:" o
do
    case "$o" in
        "h") print_help && exit 0 ;;
        "m") mode="$OPTARG" ;;
        "f") from="$OPTARG" ;;
        "t") to="$OPTARG" ;;
        "c") content="$OPTARG" ;;
        ":") echo "must supply argument to '$OPTARG'" >&2 && exit 1 ;;
        "?") echo "unknown option '$OPTARG'" >&2 && exit 1 ;;
    esac
done

shift "$(($OPTIND - 1))"

case "$mode" in
    "translate")
        post_json "$url/translate" '{
            "q": "'"$content"'",
            "source": "'"$from"'",
            "target": "'"$to"'"
        }'
        ;;
    "languages")
        curl "$url/languages"
        ;;
    "detect")
        post_json "$url/detect" '{
            "q": "'"$content"'"
        }'
    ;;
    *) echo "unknown mode '$mode'" >&2 && exit 1 ;;
esac
