#! /bin/awk -f

function help(    oldofs) {
    oldofs = OFS
    OFS = "\n"
    print "map [options]",
    "",
    "Maps an interval into another",
    "",
    "h        Prints help",
    "sx       Sets start for domain interval. Default is " sx,
    "ex       Sets end for domain interval. Default is " ex,
    "sy       Sets start for codomain interval. Default is " sy,
    "ex       Sets end for codomain interval. Default is " ey,
    "f FNAME  Applies FNAME to the result. Allowed FNAMEs are id, floor, ceil, trunc. Default is id"
    OFS = oldofs
}

function map(x) {
    return (x - sx) * (ey - sy) / (ex - sx) + sy
}

function isInt(x) {
    return x == int(x)
}

function ceil(x) {
    if (isInt(x))
        return x
    else
        return x >= 0 ? int(x + 1) : int(x)
}

function floor(x) {
    if (isInt(x))
        return x
    else
        return x >= 0 ? int(x) : int(x - 1)
}

function filterResult(x) {
    if (mode == "id") {
        return x
    } else if (mode == "floor") {
        return floor(x)
    } else if (mode == "ceil") {
        return ceil(x)
    } else if (mode == "trunc") {
        return int(x)
    } else {
        printf("operation %s not permitted\n", mode) | "cat 1>&2"
        exit 2
    }
}

BEGIN {
    sx = 0
    ex = 100
    sy = 0
    ey = 255
    mode = "id"
    for (i = 1; i < ARGC; i++) {
        if (ARGV[i] == "h") {
            help()
            exit 0
        } else if (ARGV[i] == "sx") {
            sx = ARGV[++i]
        } else if (ARGV[i] == "ex") {
            ex = ARGV[++i]
        } else if (ARGV[i] == "sy") {
            sy = ARGV[++i]
        } else if (ARGV[i] == "ey") {
            ey = ARGV[++i]
        } else if (ARGV[i] == "f") {
            mode = ARGV[++i]
        } else {
            printf("unknown option '%s'\n", ARGV[i]) | "cat 1>&2"
            exit 1
        }
    }
    ARGC = 1
}

{
    print filterResult(map($0))
}
