#! /bin/bash

print_help() {
    cat << EOF
nullshare [options] ...filelist

Upload filelist to 0x0.st (The null pointer, https://github.com/mia-0/0x0)

-h    Prints help
-t    Uploads files as archives (tar)
-x    Uploads files as gzipped archives (tar.gz). Default for directories
EOF
}

upload_file() {
    curl -s -F "file=@$1" https://0x0.st
}

print_upload_file() {
    echo -n "$1 -> "
    upload_file "$1"
}

make_tmp() {
    if [ -z "$tmpDir" ]
    then
        tmpDir="$(mktemp -d)"
    fi
}

make_tarball() {
    make_tmp
    tarballName="$(basename "$1")"
    fileName="$tmpDir/$tarballName.tar"
    tar -c -f "$fileName" "$1"
}

make_tarballgz() {
    make_tarball "$1"
    gzip "$tmpDir/$tarballName.tar"
    fileName="$tmpDir/$tarballName.tar.gz"
}

delete_tmp() {
    if [ ! -z "$tmpDir" ]
    then
        rm -rf "$tmpDir"
    fi
}

tflag=
xflag=
while getopts ":htx" o
do
    case "$o" in
        "h") print_help && exit 0 ;;
        "t") tflag=1 ;;
        "x") xflag=1 ;;
        "?") echo "unknown option '$OPTARG'" >&2 && exit 1 ;;
    esac
done

shift "$(($OPTIND - 1))"

tmpDir=
tarballName=
while [ -f "$1" -o -d "$1" ]
do
    fileName="$1"
    if [ ! -z "$xflag" -o -d "$fileName" ]
    then
        make_tarballgz "$fileName"
    elif [ ! -z "$tflag" ]
    then
        make_tarball "$fileName"
    fi
    print_upload_file "$fileName"
    shift
done

delete_tmp
