#! /bin/bash

print_help() {
    echo "shufwall [options]"
    echo ""
    echo "Sets background."
    echo "The default behaviour is to take a file from "'$WALLPAPER_DIR'" and set it as a wallpaper."
    echo ""
    echo "-h    Show this help"
    echo "-f    Specify wallpaper file instead of picking one at random"
    echo "-d    Specify wallpaper directory instead of the default "'$WALLPAPER_DIR'
}

wallpaperFile=
wallpaperDir="$WALLPAPER_DIR"
while getopts ":hf:d:" o
do
    case "$o" in
        "h") print_help && exit 0 ;;
        "f") wallpaperFile="$OPTARG" ;;
        "d") wallpaperDir="$OPTARG" ;;
        ":") echo "$o $OPTARG" ;;
        "?") echo "unknown option '$OPTARG'" >&2 && exit 1 ;;
    esac
done

if [ -z "$wallpaperFile" ]
then
    wallpaperFile="$(shuf -n1 -e "$wallpaperDir"/*)"
fi

if [ -f "$wallpaperFile" ]
then
    feh --bg-fill "$wallpaperFile"
fi
