#! /bin/awk -f

function help() {
    print "traversal [options]"
    print ""
    print "Traverses a graph."
    print ""
    print "DESCRIPTION"
    print ""
    print "Graph are specified as parent-child pairs (similarly to tsort), for example:"
    print ""
    print "1 2"
    print "1 3"
    print "2 4"
    print "2 5"
    print ""
    print "OPTIONS"
    print ""
    print "h        Prints help"
    print ""
    print "ALGO     Sets the algorithm to use (available algorithms are:"
    print "         preorder (pre), postorder (post), levelorder (level),"
    print "         topological sorting (topo))."
    print "         default is " type
    print ""
    print "-        Signals end of command line options."
    print "         After this, arguments are assumed to be files"
}

function processCLIArgs(    i, j) {
    type = "post"
    for (i = 1; i < ARGC; ++i) {
        if (ARGV[i] == "h") {
            help()
            exit 0
        } else if (ARGV[i] == "pre" || ARGV[i] == "post" || ARGV[i] == "level" || ARGV[i] == "topo") {
            type = ARGV[i]
        } else if (ARGV[i] == "-") {
            ++i
            break
        } else {
            printf("unknown option '%s'\n", ARGV[i]) | "cat 1>&2"
            exit 1
        }
    }
    for (j = 1; j < i; ++j) {
        ARGV[j] = ""
    }
}

# deque data structure

function deque(deq) {
    deq["start"] = 0
    deq["end"] = 0
}

function dlength(deq) {
    return deq["end"] - deq["start"]
}

function push(deq, elem) {
    deq[deq["end"]++] = elem
}

function pop(deq, elem) {
    if (dlength(deq) > 0) {
        return deq[--deq["end"]]
    }
}

function last(deq) {
    if (dlength(deq) > 0) {
        return deq[deq["end"] - 1]
    }
}

function unshift(deq, elem) {
    deq[--deq["start"]] = elem
}

function shift(deq) {
    if (dlength(deq)) {
        return deq[deq["start"]++]
    }
}

function first(deq) {
    if (dlength(deq)) {
        return deq[deq["first"]]
    }
}

# graph data structure

function graph(gr) {
    split("", gr)
}

function hasNode(gr, node) {
    return node in gr
}

function nchildren(gr, node) {
    return gr[node, "nchildren"]
}

function nthchild(gr, node, i) {
    return gr[node, "child", i]
}

function addNode(gr, node) {
    gr[node] = 1
    gr[node, "nchildren"] = 0
}

function addChild(gr, node, child) {
    if (!hasNode(gr, node)) {
        addNode(gr, node)
    }
    if (!hasNode(gr, child)) {
        addNode(gr, child)
    }
    gr[node, "child", ++gr[node, "nchildren"]] = child
}

# algorithms

function postorder(gr, starting, deq, visited, done,    node, childrenDone, i, child) {
    push(deq, starting)
    while (dlength(deq) > 0) {
        node = last(deq)
        visited[node] = 1
        childrenDone = 1
        for (i = nchildren(gr, node); i >= 1; --i) {
            child =  nthchild(gr, node, i)
            if (visited[child] && !done[child]) {
                printf("cycle detected at %s\n", child)
                continue
            }
            if (!done[child]) {
                childrenDone = 0
                push(deq, child)
            }
        }
        if (childrenDone) {
            printf("%s\n", node)
            pop(deq)
            done[node] = 1
        }
    } 
}

function preorder(gr, starting, deq, visited,    node, i, child) {
    push(deq, starting)
    while (dlength(deq) > 0) {
        node = pop(deq)
        visited[node] = 1
        printf("%s\n", node)
        for (i = nchildren(gr, node); i >= 1; --i) {
            child =  nthchild(gr, node, i)
            if (visited[child]) {
                printf("cycle detected at %s\n", child)
                continue
            }
            push(deq, child)
        }
    }
}

function levelorder(gr, starting, deq, visited,    node, i, j, nlevel, delim) {
    push(deq, starting)
    while (dlength(deq) > 0) {
        nlevel = dlength(deq)
        delim = ""
        for (i = 1; i <= nlevel; ++i) {
            node = shift(deq)
            visited[node] = 1
            printf("%s%s", delim, node)
            delim = " "
            for (j = nchildren(gr, node); j >= 1; --j) {
                child =  nthchild(gr, node, j)
                if (visited[child]) {
                    printf("\ncycle detected at %s", child)
                    continue
                }
                push(deq, child)
            }
        }
        printf("\n")
    }
}

function algorithm(type, gr, root) {
    delete deq
    delete visited
    deque(deq)
    if (type == "post") {
        delete done
        postorder(gr, root, deq, visited, done)
    } else if (type == "topo") {
        postorder(gr, root, deq, visited, done)
    } else if (type == "pre") {
        preorder(gr, root, deq, visited)
    } else if (type == "level") {
        levelorder(gr, root, deq, visited)
    }
}

function delimitBreaks(type, delimiter) {
    if (type == "post" || type == "pre" || type == "level") {
        printf("%s", delimiter)
    } 
}

# main

BEGIN {
    processCLIArgs()
}

{
    gsub(/^\s+/, "")
    gsub(/\s$/, "")
    if (length($0) == 0)
        next

    for (i = 1; i <= NF; ++i) {
        if (!prevroot) {
            if ($i in leaves) {
                delete roots[$i]
            } else {
                roots[$i] = 1
            }
            prevroot = $i
        } else {
            leaves[$i] = 1
            addChild(gr, prevroot, $i)
            prevroot = ""
        }
    }
}

END {
    if (prevroot) {
        printf("odd number of nodes\n") | "cat 1>&2"
        exit 1
    }
    delim = ""
    for (root in roots) {
        delimitBreaks(type, delim)
        algorithm(type, gr, root)
        delim = "\n"
    }        
}
