#! /bin/awk -f

function help() {
    print "traversal [options]"
    print ""
    print "Traverses a graph."
    print ""
    print "DESCRIPTION"
    print ""
    print "Graph are specified as parent-child pairs (similarly to tsort), for example:"
    print ""
    print "1 2"
    print "1 3"
    print "2 4"
    print "2 5"
    print ""
    print "OPTIONS"
    print ""
    print "h             Prints help"
    print ""
    print "type ALGO     Sets the algorithm to use (available algorithms are:"
    print "              preorder (pre), postorder (post), levelorder (level))."
    print "              default is " type
    print ""
    print "-             Signals end of command line options."
    print "              After this, arguments are assumed to be files"
}

function processCLIArgs(    i, j) {
    type = "post"
    for (i = 1; i < ARGC; ++i) {
        if (ARGV[i] == "h") {
            help()
            exit 0
        } else if (ARGV[i] == "type") {
            ++i
            if (ARGV[i] == "pre" || ARGV[i] == "post" || ARGV[i] == "level") {
                type = ARGV[i]
            } else {
                printf("unknown algorithm '%s'\n", ARGV[i]) | "cat 1>&2"
                exit 1
            }
        } else if (ARGV[i] == "-") {
            ++i
            break
        } else {
            printf("unknown option '%s'\n", ARGV[i]) | "cat 1>&2"
            exit 1
        }
    }
    for (j = 1; j < i; ++j) {
        ARGV[j] = ""
    }
}

# deque data structure

function deque(deq) {
    deq["start"] = 0
    deq["end"] = 0
}

function dlength(deq) {
    return deq["end"] - deq["start"]
}

function push(deq, elem) {
    deq[deq["end"]++] = elem
}

function pop(deq, elem) {
    if (dlength(deq) > 0) {
        return deq[--deq["end"]]
    }
}

function last(deq) {
    if (dlength(deq) > 0) {
        return deq[deq["end"] - 1]
    }
}

function unshift(deq, elem) {
    deq[--deq["start"]] = elem
}

function shift(deq) {
    if (dlength(deq)) {
        return deq[deq["start"]++]
    }
}

function first(deq) {
    if (dlength(deq)) {
        return deq[deq["first"]]
    }
}

# graph data structure

function graph(gr) {
    split("", gr)
}

function hasNode(gr, node) {
    return node in gr
}

function nchildren(gr, node) {
    return gr[node, "nchildren"]
}

function nthchild(gr, node, i) {
    return gr[node, "child", i]
}

function addNode(gr, node) {
    gr[node] = 1
    gr[node, "nchildren"] = 0
}

function addChild(gr, node, child) {
    if (!hasNode(gr, node)) {
        addNode(gr, node)
    }
    if (!hasNode(gr, child)) {
        addNode(gr, child)
    }
    gr[node, "child", ++gr[node, "nchildren"]] = child
}

# algorithms

function postorder(gr, starting, deq, visited, done,    node, childrenDone, i, child) {
    push(deq, starting)
    while (dlength(deq) > 0) {
        node = last(deq)
        visited[node] = 1
        childrenDone = 1
        for (i = nchildren(gr, node); i >= 1; --i) {
            child =  nthchild(gr, node, i)
            if (visited[child] && !done[child]) {
                printf("cycle detected at %s\n", child)
                continue
            }
            if (!done[child]) {
                childrenDone = 0
                push(deq, child)
            }
        }
        if (childrenDone) {
            printf("%s\n", node)
            pop(deq)
            done[node] = 1
        }
    } 
}

function preorder(gr, starting, deq, visited,    node, i, child) {
    push(deq, starting)
    while (dlength(deq) > 0) {
        node = pop(deq)
        visited[node] = 1
        printf("%s\n", node)
        for (i = nchildren(gr, node); i >= 1; --i) {
            child =  nthchild(gr, node, i)
            if (visited[child]) {
                printf("cycle detected at %s\n", child)
                continue
            }
            push(deq, child)
        }
    }
}

function levelorder(gr, starting, deq, visited,    node, i, j, nlevel, delim) {
    push(deq, starting)
    while (dlength(deq) > 0) {
        nlevel = dlength(deq)
        delim = ""
        for (i = 1; i <= nlevel; ++i) {
            node = shift(deq)
            visited[node] = 1
            printf("%s%s", delim, node)
            delim = " "
            for (j = nchildren(gr, node); j >= 1; --j) {
                child =  nthchild(gr, node, j)
                if (visited[child]) {
                    printf("\ncycle detected at %s", child)
                    continue
                }
                push(deq, child)
            }
        }
        printf("\n")
    }
}

function algorithm(type, gr, root, deq, visited, done) {
    if (type == "post") {
        postorder(gr, root, deq, visited, done)
    } else if (type == "pre") {
        preorder(gr, root, deq, visited)
    } else if (type == "level") {
        levelorder(gr, root, deq, visited)
    }
}

# main

BEGIN {
    processCLIArgs()
}

{
    if ($1 in leaves) {
        delete roots[$1]
    } else {
        roots[$1] = 1
    }
    leaves[$2] = 1
    addChild(gr, $1, $2)    
}

END {
    delim = ""
    for (root in roots) {
        printf("%s", delim)
        delim = "\n"
        deque(deq)
        algorithm(type, gr, root, deq, visited, done)
    }        
}
