bindgesture --exact swipe:3:left focus next sibling
bindgesture --exact swipe:3:right focus prev sibling
bindgesture --exact swipe:3:up workspace next_on_output
bindgesture --exact swipe:3:down workspace prev_on_output

bindsym --no-warn $mod+o exec swaymsg move container to output "$(~/.config/sway/scripts/output-next)" \; focus output "$(~/.config/sway/scripts/output-next)"
bindsym --no-warn $mod+Shift+o exec swaymsg move workspace to output "$(~/.config/sway/scripts/output-next)" \; focus output "$(~/.config/sway/scripts/output-next)"
bindsym --no-warn $mod+u exec swaymsg focus output "$(~/.config/sway/scripts/output-next)"
