bindgesture --exact swipe:3:left focus next sibling
bindgesture --exact swipe:3:right focus prev sibling
bindgesture --exact swipe:3:up workspace next_on_output
bindgesture --exact swipe:3:down workspace prev_on_output

