exec gammastep-indicator
exec nm-applet
exec xfce4-volumed-pulse
exec xfce4-power-manager
# https://github.com/sentriz/cliphist
exec wl-paste --watch cliphist store

bindsym XF86AudioRaiseVolume exec myvolume up 5%
bindsym XF86AudioLowerVolume exec myvolume down 5%
bindsym XF86AudioMute exec myvolume mute
bindsym XF86AudioMicMute exec exec myvolume mic-mute
bindsym XF86MonBrightnessDown exec mybrightness down
bindsym XF86MonBrightnessUp exec mybrightness up

bindsym $mod+z exec wooz
